name: ci

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install uv, tox
        run: |
          python -m pip install --upgrade pip
          pip install uv
          uv tool install tox --with tox-uv

      - name: Sync dependencies
        run: uv sync

      - name: Run tests with tox
        run: tox